In [11]:
# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np

# Uso de API's
# -----------------------------------------------------------------------
import requests

# Para incluir una barra de proceso en for loops
# -----------------------------------------------------------------------
from tqdm import tqdm


# Para introducir tiempo entre las llamadas
# -----------------------------------------------------------------------
from time import sleep


# Para trabajar con archivos dotenv y los tokens
# -----------------------------------------------------------------------
import os
import dotenv
# dotenv.load_dotenv() ### reconoce un archivo .env y que tiene información

from time import sleep
import json

In [3]:

url = "https://basketapi1.p.rapidapi.com/api/basketball/tournament/132/season/38191/standings/total"

headers = {
	"x-rapidapi-key": "8bf68f7481msh7aa93c8e8e9a6ffp19eef8jsn33f2cc37fe85",
	"x-rapidapi-host": "basketapi1.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

responsa = response.json()
#extraccion de los standings en la 2002/2003

In [12]:
with open('league_2003.json', 'w') as archivo_json:
    json.dump(responsa, archivo_json, indent=4)

In [4]:
responsa.keys()

dict_keys(['standings'])

In [42]:
responsa['standings'][8]['rows'][0]
#hasta aquí tengo el standings general de los equipos. Con el 0 me meto en el equipo 1

{'team': {'name': 'Phoenix Suns',
  'slug': 'phoenix-suns',
  'shortName': 'Suns',
  'gender': 'M',
  'sport': {'name': 'Basketball', 'slug': 'basketball', 'id': 2},
  'userCount': 53221,
  'nameCode': 'PHX',
  'disabled': False,
  'national': False,
  'type': 0,
  'id': 3416,
  'teamColors': {'primary': '#e56020',
   'secondary': '#1d1160',
   'text': '#1d1160'},
  'fieldTranslations': {'nameTranslation': {'ar': 'فونيكس سانز',
    'ru': 'Финикс Санс'},
   'shortNameTranslation': {}}},
 'descriptions': [],
 'position': 1,
 'matches': 82,
 'wins': 64,
 'scoresFor': 9416,
 'scoresAgainst': 8801,
 'percentage': 0.78,
 'gamesBehind': 0,
 'streak': -1,
 'id': 694091,
 'losses': 18,
 'draws': 0,
 'scoreDiffFormatted': '+615'}

In [43]:
responsa['standings'][8]['rows'][0]['percentage']

0.78

In [44]:
nombre_equipo = responsa['standings'][8]['rows'][0]['team']['name']
nombre_corto = responsa['standings'][8]['rows'][0]['team']['shortName']
name_code = responsa['standings'][8]['rows'][0]['team']['nameCode']
position = responsa['standings'][8]['rows'][0]['position']
partidos = responsa['standings'][8]['rows'][0]['matches']
victorias= responsa['standings'][8]['rows'][0]['wins']
derrotas = responsa['standings'][8]['rows'][0]['losses']
per_vic = responsa['standings'][8]['rows'][0]['percentage']

In [45]:
lista_diccionario = []
for i in range(0,30):
    nombre_equipo = responsa['standings'][8]['rows'][i]['team']['name']
    nombre_corto = responsa['standings'][8]['rows'][i]['team']['shortName']
    name_code = responsa['standings'][8]['rows'][i]['team']['nameCode']
    position = responsa['standings'][8]['rows'][i]['position']
    partidos = responsa['standings'][8]['rows'][i]['matches']
    victorias= responsa['standings'][8]['rows'][i]['wins']
    derrotas = responsa['standings'][8]['rows'][i]['losses']
    per_vic = responsa['standings'][8]['rows'][i]['percentage']
    diccionario = {'Equipo': nombre_equipo, 
                   'Nombre_comun': nombre_corto,
                   'Codigo_equipo' : name_code,
                   'Posicion': position, 
                   'Partidos': partidos,
                   'Victorias': victorias,
                   'Derrotas': derrotas,
                   'Porcentaje_vic': per_vic}
    lista_diccionario.append(diccionario)

In [46]:
df = pd.DataFrame(lista_diccionario)

In [47]:
df

,Equipo,Nombre_comun,Codigo_equipo,Posicion,Partidos,Victorias,Derrotas,Porcentaje_vic
0,Phoenix Suns,Suns,PHX,1,82,64,18,0.780
1,Memphis Grizzlies,Grizzlies,MEM,2,82,56,26,0.683
2,Golden State Warriors,Warriors,GSW,3,82,53,29,0.646
3,Miami Heat,Heat,MIA,4,82,53,29,0.646
4,Dallas Mavericks,Mavericks,DAL,5,82,52,30,0.634
5,Boston Celtics,Celtics,BOS,6,82,51,31,0.622
6,Milwaukee Bucks,Bucks,MIL,7,82,51,31,0.622
7,Philadelphia 76ers,76ers,PHI,8,82,51,31,0.622
8,Utah Jazz,Jazz,UTA,9,82,49,33,0.598
9,Denver Nuggets,Nuggets,DEN,10,82,48,34,0.585
10,Toronto Raptors,Raptors,TOR,11,82,48,34,0.585
11,Chicago Bulls,Bulls,CHI,12,82,46,36,0.561
12,Minnesota Timberwolves,Timberwolves,MIN,13,82,46,36,0.561
13,Brooklyn Nets,Nets,BKN,14,82,44,38,0.537
14,Cleveland Cavaliers,Cavaliers,CLE,15,82,44,38,0.537
15,Atlanta Hawks,Hawks,ATL,16,82,43,39,0.524
16,Charlotte Hornets,Hornets,CHA,17,82,43,39,0.524
17,Los Angeles Clippers,Clippers,LAC,18,82,42,40,0.512
18,New York Knicks,Knicks,NYK,19,82,37,45,0.451
19,New Orleans Pelicans,Pelicans,NOP,20,82,36,46,0.439
20,Washington Wizards,Wizards,WAS,21,82,35,47,0.427
21,San Antonio Spurs,Spurs,SAS,22,82,34,48,0.415
22,Los Angeles Lakers,Lakers,LAL,23,82,33,49,0.402
23,Sacramento Kings,Kings,SAC,24,82,30,52,0.366
24,Portland Trail Blazers,Trail Blazers,POR,25,82,27,55,0.329
25,Indiana Pacers,Pacers,IND,26,82,25,57,0.305
26,Oklahoma City Thunder,Thunder,OKC,27,82,24,58,0.293
27,Detroit Pistons,Pistons,DET,28,82,23,59,0.280
28,Orlando Magic,Magic,ORL,29,82,22,60,0.268
29,Houston Rockets,Rockets,HOU,30,82,20,62,0.244