In [2]:
pip install nba_api

Collecting nba_api
  Downloading nba_api-1.6.1-py3-none-any.whl.metadata (5.5 kB)
Collecting numpy<2.0.0,>=1.22.2 (from nba_api)
  Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from nba_api) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dell\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2024.8.30)
Downloading nba_api-1.6.1-py3-none-any.whl (279 kB)
Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   -- ------------------------------------- 1.0/15.8 MB 7.2 MB/s eta 0:00:03
   ------ --------------------------------- 2.6/15.8 MB 7.2 MB/s eta 0:00:02
   ---------- ----------------------------- 4.2/15.8 MB 7.6 MB/s eta 0:00:02
   --------------- ------------------------ 6.0/15.8 MB 7.7 MB/s eta 0:00:02
   ------------------ --------------------- 7.3/15.8 MB 7.3 MB/s eta 0:00:02
   --------------------- ------------------ 8.4/15.8 MB 6.9 MB/s eta 0:00:02
   ----------------------- ---------------- 9.2/15.8 MB 6.8 MB/s eta 0:00:01
   ------------------------ --------------- 9.7/15.8 MB 5.9 MB/s eta 0:00:02
   --------------------------- ------------ 11.0/15.8 MB 6.0 MB/s eta 0:00:01
   --------------------------------- ------ 13.1/15.8 MB 6.4 MB/s eta 0:00:01
   -------------------------------------- - 15.2/15.8 MB 6.7 MB/s eta 0:00:01
   ---------------------------------------- 15.8/15.8 MB 6.7 MB/s eta 0:00:00
Installing collected packages: numpy, nba_api
  Attempting uninstall: numpy
    Found existing installation: numpy 2.1.2
    Uninstalling numpy-2.1.2:
      Successfully uninstalled numpy-2.1.2
Successfully installed nba_api-1.6.1 numpy-1.26.4
Note: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\DELL\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\~umpy'.
  You can safely remove it manually.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Users\DELL\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
from nba_api.stats.endpoints import leaguedashplayerstats
from nba_api.stats.endpoints import playercareerstats
import pandas as pd

In [4]:
pd.set_option('display.max_rows', None)       # Show all rows
pd.set_option('display.max_columns', None)    # Show all columns
pd.set_option('display.width', 1000)          # Set the width to accommodate more columns
pd.set_option('display.max_colwidth', None)   # Set maximum column width to None (auto adjust)
pd.set_option('display.float_format', '{:.2f}'.format)

In [5]:


# Define the seasons for the Jordan and LeBron eras
jordan_era_seasons = [
    '1984-85', '1985-86', '1986-87', '1987-88', '1988-89', '1989-90', '1990-91', '1991-92', '1992-93',
    '1994-95', '1995-96', '1996-97', '1997-98'
]
lebron_era_seasons = [
    '2003-04', '2004-05', '2005-06', '2006-07', '2007-08', '2008-09', '2009-10', '2010-11', '2011-12', 
    '2012-13', '2013-14', '2014-15', '2015-16', '2016-17', '2017-18', '2018-19', '2019-20', '2020-21', 
    '2021-22', '2022-23'
]

# Initialize empty lists to store data
jordan_era_data = []
lebron_era_data = []

# Fetch league-wide stats for Jordan Era
for season in jordan_era_seasons:
    stats = leaguedashplayerstats.LeagueDashPlayerStats(season=season)
    stats_df = stats.get_data_frames()[0]
    stats_df['SEASON'] = season
    jordan_era_data.append(stats_df)

# Fetch league-wide stats for LeBron Era
for season in lebron_era_seasons:
    stats = leaguedashplayerstats.LeagueDashPlayerStats(season=season)
    stats_df = stats.get_data_frames()[0]
    stats_df['SEASON'] = season
    lebron_era_data.append(stats_df)

# Combine each era's data into single DataFrames
jordan_era_stats_df = pd.concat(jordan_era_data, ignore_index=True)
lebron_era_stats_df = pd.concat(lebron_era_data, ignore_index=True)

# Display first few rows of each era's data
jordan_era_stats_df.head(), lebron_era_stats_df.head()

C:\Users\DELL\AppData\Local\Temp\ipykernel_8288\1711564547.py:31: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  jordan_era_stats_df = pd.concat(jordan_era_data, ignore_index=True)

(  PLAYER_ID     PLAYER_NAME NICKNAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP   W   L  W_PCT     MIN  FGM  FGA  FG_PCT FG3M FG3A  FG3_PCT  FTM  FTA  FT_PCT OREB DREB  REB  AST TOV STL BLK BLKA   PF PFD  PTS PLUS_MINUS  NBA_FANTASY_PTS DD2 TD3  WNBA_FANTASY_PTS GP_RANK W_RANK L_RANK W_PCT_RANK MIN_RANK FGM_RANK FGA_RANK FG_PCT_RANK FG3M_RANK FG3A_RANK FG3_PCT_RANK FTM_RANK FTA_RANK FT_PCT_RANK OREB_RANK DREB_RANK REB_RANK AST_RANK TOV_RANK STL_RANK BLK_RANK BLKA_RANK PF_RANK PFD_RANK PTS_RANK PLUS_MINUS_RANK NBA_FANTASY_PTS_RANK DD2_RANK TD3_RANK WNBA_FANTASY_PTS_RANK   SEASON
 0       920      A.C. Green     A.C.  1610612742               DAL 33.00  83  23  60   0.28 2494.30  234  484    0.48    1   20     0.05  128  197    0.65  222  434  656   69  74  70  16   43  145   4  597       -350          1671.70  16   0           1495.00       1    238    423        354       77      152      155         101       271       227          302      130      120         318        21        28       28      209      196       98      202       342     272       18      151             421                  117       49       24                   135  1996-97
 1       243     Aaron McKie    Aaron  1610612765               DET 24.00  83  48  35   0.58 1623.91  150  365    0.41   41  103     0.40   92  110    0.84   40  181  221  161  90  77  22   36  130   0  433        133          1146.70   1   0           1054.00       1     67    303        158      168      203      196         302       127       134           63      172      186          60       228       148      168      110      165       85      155       319     247      192      195              70                  180      168       24                   181  1996-97
 2      1425  Aaron Williams    Aaron  1610612763               VAN 25.00  33   4  29   0.12  562.42   85  148    0.57    0    1     0.00   33   49    0.67   62   81  143   15  32  16  29    7   72   0  203       -104           500.10   0   0            451.00     329    392    256        425      301      273      302           8       303       341          303      290      285         296       173       265      232      340      292      290      120       117     152      192      284             337                  282      219       24                   287  1996-97
 3       768       Acie Earl     Acie  1610612749               MIL 27.00  47  14  33   0.30  500.14   67  179    0.37    0    5     0.00   54   84    0.64   35   61   96   20  35  15  28    8   61   0  188        -60           427.20   0   0            390.00     287    308    285        342      311      297      281         381       303       287          303      234      223         324       248       297      289      324      284      299      123       126     140      192      290             303                  300      219       24                   301  1996-97
 4       228      Adam Keefe     Adam  1610612762               UTA 27.00  62  48  14   0.77  916.79   82  160    0.51    0    1     0.00   71  103    0.69   75  141  216   32  45  30  13   13   97   1  235        122           626.20   1   0            569.00     215     67    115         39      252      274      292          52       303       341          303      197      197         278       147       185      173      289      261      228      222       169     183       90      270              74                  258      168       24                   261  1996-97,
    PLAYER_ID     PLAYER_NAME NICKNAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP   W   L  W_PCT     MIN  FGM  FGA  FG_PCT  FG3M  FG3A  FG3_PCT  FTM  FTA  FT_PCT  OREB  DREB  REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  PLUS_MINUS  NBA_FANTASY_PTS  DD2  TD3  WNBA_FANTASY_PTS  GP_RANK  W_RANK  L_RANK  W_PCT_RANK  MIN_RANK  FGM_RANK  FGA_RANK  FG_PCT_RANK  FG3M_RANK  FG3A_RANK  FG3_PCT_RANK  FTM_RANK  FTA_RANK  FT_PCT_RANK  OREB_RANK  DREB_RANK  REB_RANK  AST_RANK  TOV_RANK  STL_RANK  BLK_RANK  BLKA_RANK  PF_RANK  PFD_RANK  PTS_RANK  PLUS_MINUS_RANK  NBA_FANTASY_PTS_RANK  DD2_RANK  TD3_RANK  WNBA_FANTASY_PTS_RANK   SEASON
 0        243     Aaron McKie    Aaron  1610612755               PHI 31.00  75  30  45   0.40 2116.93  265  577    0.46    75   172     0.44   84  111    0.76    45   208  253  195  103   85   23    52  142    0   689         -42          1506.10    0    0           1428.00      120     191     388         310       110       125       133          138         66         86            24       178       186          194        221        138       168        91       131        65       137        375      266        79       127              269                   124       235        19                    124  2003-04
 1       1425  Aaron Williams    Aaron  1610612751               NJN 32.00  72  39  33   0.54 1335.85  172  342    0.50     1     3     0.33  105  155    0.68   101   193  294   81   89   34   46    20  187    0   450         -50          1075.30    1    0            986.00      147     105     273         151       202       190       216           37        258        286           138       148       138          302         97        153       131       200       158       216        76        219      352        79       192              287                   189       178        19                    194  2003-04
 2       1502    Adonal Foyle   Adonal  1610612744               GSW 29.00  44  21  23   0.48  574.57   59  130    0.45     0     0     0.00   19   35    0.54    54   113  167   17   21    6   46    11   68    0   137         -83           497.90    2    0            425.00      298     276     157         228       310       319       325          149        289        361           289       333       312          388        190        243       231       338       337       362        76        142      146        79       325              337                   287       146        19                    297  2003-04
 3       1559  Adrian Griffin   Adrian  1610612745               HOU 29.00  19  13   6   0.68  122.09    5   18    0.28     1     2     0.50    0    4    0.00     1    18   19   10    3    7    2     0   17    0    11         -47            72.80    0    0             59.00      373     337      49          53       386       405       400          421        258        305             5       425       400          425        413        375       380       368       405       355       356          1       63        79       410              281                   386       235        19                    388  2003-04
 4       1733   Al Harrington       Al  1610612754               IND 24.00  79  58  21   0.73 2440.86  421  909    0.46    21    77     0.27  185  252    0.73   163   345  508  131  163   80   22    80  250    0  1048          71          1997.10   12    0           1912.00       77       4     141          28        77        56        64          128        146        140           214        76        73          245         43         50        45       141        59        80       139        422      423        79        68               93                    85        47        19                     81  2003-04)

In [6]:
jordan_era_stats_df.columns

Index(['PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS', 'NBA_FANTASY_PTS', 'DD2', 'TD3', 'WNBA_FANTASY_PTS', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK', 'DD2_RANK', 'TD3_RANK', 'WNBA_FANTASY_PTS_RANK', 'SEASON'], dtype='object')

In [7]:
# Lista de columnas a eliminar
columns_to_drop = [
    'NBA_FANTASY_PTS', 'DD2', 'TD3', 'WNBA_FANTASY_PTS', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK',
    'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK',
    'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK', 
    'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK', 'PTS_RANK', 
    'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK', 'DD2_RANK', 'TD3_RANK', 'WNBA_FANTASY_PTS_RANK'
]

# Elimina las columnas del DataFrame (ejemplo con jordan_era_stats_df)
jordan_era_stats_df = jordan_era_stats_df.drop(columns=columns_to_drop, axis=1)
lebron_era_stats_df = lebron_era_stats_df.drop(columns=columns_to_drop, axis=1)

# Muestra los primeros registros para verificar que las columnas han sido eliminadas
jordan_era_stats_df.head(), lebron_era_stats_df.head()

(  PLAYER_ID     PLAYER_NAME NICKNAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP   W   L  W_PCT     MIN  FGM  FGA  FG_PCT FG3M FG3A  FG3_PCT  FTM  FTA  FT_PCT OREB DREB  REB  AST TOV STL BLK BLKA   PF PFD  PTS PLUS_MINUS   SEASON
 0       920      A.C. Green     A.C.  1610612742               DAL 33.00  83  23  60   0.28 2494.30  234  484    0.48    1   20     0.05  128  197    0.65  222  434  656   69  74  70  16   43  145   4  597       -350  1996-97
 1       243     Aaron McKie    Aaron  1610612765               DET 24.00  83  48  35   0.58 1623.91  150  365    0.41   41  103     0.40   92  110    0.84   40  181  221  161  90  77  22   36  130   0  433        133  1996-97
 2      1425  Aaron Williams    Aaron  1610612763               VAN 25.00  33   4  29   0.12  562.42   85  148    0.57    0    1     0.00   33   49    0.67   62   81  143   15  32  16  29    7   72   0  203       -104  1996-97
 3       768       Acie Earl     Acie  1610612749               MIL 27.00  47  14  33   0.30  500.14   67  179    0.37    0    5     0.00   54   84    0.64   35   61   96   20  35  15  28    8   61   0  188        -60  1996-97
 4       228      Adam Keefe     Adam  1610612762               UTA 27.00  62  48  14   0.77  916.79   82  160    0.51    0    1     0.00   71  103    0.69   75  141  216   32  45  30  13   13   97   1  235        122  1996-97,
    PLAYER_ID     PLAYER_NAME NICKNAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP   W   L  W_PCT     MIN  FGM  FGA  FG_PCT  FG3M  FG3A  FG3_PCT  FTM  FTA  FT_PCT  OREB  DREB  REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  PLUS_MINUS   SEASON
 0        243     Aaron McKie    Aaron  1610612755               PHI 31.00  75  30  45   0.40 2116.93  265  577    0.46    75   172     0.44   84  111    0.76    45   208  253  195  103   85   23    52  142    0   689         -42  2003-04
 1       1425  Aaron Williams    Aaron  1610612751               NJN 32.00  72  39  33   0.54 1335.85  172  342    0.50     1     3     0.33  105  155    0.68   101   193  294   81   89   34   46    20  187    0   450         -50  2003-04
 2       1502    Adonal Foyle   Adonal  1610612744               GSW 29.00  44  21  23   0.48  574.57   59  130    0.45     0     0     0.00   19   35    0.54    54   113  167   17   21    6   46    11   68    0   137         -83  2003-04
 3       1559  Adrian Griffin   Adrian  1610612745               HOU 29.00  19  13   6   0.68  122.09    5   18    0.28     1     2     0.50    0    4    0.00     1    18   19   10    3    7    2     0   17    0    11         -47  2003-04
 4       1733   Al Harrington       Al  1610612754               IND 24.00  79  58  21   0.73 2440.86  421  909    0.46    21    77     0.27  185  252    0.73   163   345  508  131  163   80   22    80  250    0  1048          71  2003-04)

In [30]:
jordan_era_stats_df.shape

(880, 33)

In [9]:
jordan_era_stats_df['TEAM_ABBREVIATION'].unique()

array(['DAL', 'DET', 'VAN', 'MIL', 'UTA', 'PHI', 'ATL', 'POR', 'NYK',
       'MIA', 'BOS', 'ORL', 'GSW', 'DEN', 'CHH', 'IND', 'SEA', 'CLE',
       'WAS', 'SAS', 'PHX', 'TOR', 'CHI', 'SAC', 'LAC', 'HOU', 'LAL',
       'MIN', 'NJN'], dtype=object)

In [12]:
jordan_era_stats_df[jordan_era_stats_df['PLAYER_NAME'] == 'Michael Jordan']

    PLAYER_ID     PLAYER_NAME NICKNAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP   W   L  W_PCT     MIN  FGM   FGA  FG_PCT FG3M FG3A  FG3_PCT  FTM  FTA  FT_PCT OREB DREB  REB  AST  TOV  STL BLK BLKA   PF PFD   PTS PLUS_MINUS   SEASON
308       893  Michael Jordan  Michael  1610612741               CHI 34.00  82  69  13   0.84 3108.80  920  1892    0.49  111  297     0.37  480  576    0.83  113  369  482  352  166  140  44   49  156   2  2431        820  1996-97
744       893  Michael Jordan  Michael  1610612741               CHI 35.00  82  62  20   0.76 3182.38  881  1893    0.47   30  126     0.24  565  721    0.78  130  345  475  283  185  141  45   73  151   2  2357        598  1997-98

In [20]:
jordan_era_stats_df['TEAM_ABBREVIATION'].unique()

array(['DAL', 'DET', 'VAN', 'MIL', 'UTA', 'PHI', 'ATL', 'POR', 'NYK',
       'MIA', 'BOS', 'ORL', 'GSW', 'DEN', 'CHH', 'IND', 'SEA', 'CLE',
       'WAS', 'SAS', 'PHX', 'TOR', 'CHI', 'SAC', 'LAC', 'HOU', 'LAL',
       'MIN', 'NJN'], dtype=object)

In [21]:
jordan_era_stats_df['TEAM_ABBREVIATION'].nunique()

29

In [22]:
lebron_era_stats_df['TEAM_ABBREVIATION'].nunique()

34

In [24]:
lebron_era_stats_df['TEAM_ABBREVIATION'].unique()

array(['PHI', 'NJN', 'GSW', 'HOU', 'IND', 'ATL', 'SAS', 'NYK', 'TOR',
       'PHX', 'DEN', 'UTA', 'ORL', 'SEA', 'DAL', 'SAC', 'CHI', 'NOH',
       'DET', 'MIA', 'MEM', 'LAC', 'BOS', 'WAS', 'MIL', 'LAL', 'CLE',
       'POR', 'MIN', 'CHA', 'NOK', 'OKC', 'BKN', 'NOP'], dtype=object)

In [14]:
lebron_era_stats_df[lebron_era_stats_df['PLAYER_NAME'] == 'LeBron James']

      PLAYER_ID   PLAYER_NAME NICKNAME     TEAM_ID TEAM_ABBREVIATION   AGE  GP   W   L  W_PCT     MIN  FGM   FGA  FG_PCT  FG3M  FG3A  FG3_PCT  FTM  FTA  FT_PCT  OREB  DREB  REB  AST  TOV  STL  BLK  BLKA   PF  PFD   PTS  PLUS_MINUS   SEASON
247        2544  LeBron James   LeBron  1610612739               CLE 19.00  79  33  46   0.42 3126.86  622  1492    0.42    63   217     0.29  347  460    0.75    99   333  432  465  273  130   58    76  149    0  1654        -144  2003-04
709        2544  LeBron James   LeBron  1610612739               CLE 20.00  80  41  39   0.51 3383.97  795  1684    0.47   108   308     0.35  477  636    0.75   111   477  588  577  262  177   52    71  146    0  2175         151  2004-05
1173       2544  LeBron James   LeBron  1610612739               CLE 21.00  79  47  32   0.59 3360.62  875  1823    0.48   127   379     0.34  601  814    0.74    75   481  556  521  260  123   66    65  181  591  2478         275  2005-06
1624       2544  LeBron James   LeBron  1610612739               CLE 22.00  78  47  31   0.60 3190.29  772  1621    0.48    99   310     0.32  489  701    0.70    83   443  526  470  250  125   55    49  171  517  2132         378  2006-07
2085       2544  LeBron James   LeBron  1610612739               CLE 23.00  75  45  30   0.60 3026.80  794  1642    0.48   113   359     0.32  549  771    0.71   133   459  592  539  255  138   81    61  165  590  2250         138  2007-08
2528       2544  LeBron James   LeBron  1610612739               CLE 24.00  81  66  15   0.81 3054.06  789  1613    0.49   132   384     0.34  594  762    0.78   106   507  613  587  241  137   93    59  139  583  2304         872  2008-09
2978       2544  LeBron James   LeBron  1610612739               CLE 25.00  76  60  16   0.79 2965.73  768  1528    0.50   129   387     0.33  593  773    0.77    71   483  554  651  261  125   77    43  119  531  2258         650  2009-10
3433       2544  LeBron James   LeBron  1610612748               MIA 26.00  79  57  22   0.72 3062.98  758  1485    0.51    92   279     0.33  503  663    0.76    80   510  590  554  284  124   50    38  163  466  2111         619  2010-11
3917       2544  LeBron James   LeBron  1610612748               MIA 27.00  62  45  17   0.73 2326.22  621  1169    0.53    54   149     0.36  387  502    0.77    94   398  492  387  213  115   50    31   96  379  1683         474  2011-12
4386       2544  LeBron James   LeBron  1610612748               MIA 28.00  76  61  15   0.80 2877.05  765  1354    0.56   103   254     0.41  403  535    0.75    97   513  610  551  226  129   67    41  110  439  2036         720  2012-13
4846       2544  LeBron James   LeBron  1610612748               MIA 29.00  77  52  25   0.68 2901.87  767  1353    0.57   116   306     0.38  439  585    0.75    81   452  533  488  270  121   26    42  126  459  2089         409  2013-14
5342       2544  LeBron James   LeBron  1610612739               CLE 30.00  69  50  19   0.72 2493.42  624  1279    0.49   120   339     0.35  375  528    0.71    51   365  416  511  272  109   49    48  135  412  1743         541  2014-15
5824       2544  LeBron James   LeBron  1610612739               CLE 31.00  76  56  20   0.74 2708.58  737  1416    0.52    87   282     0.31  359  491    0.73   111   454  565  514  249  104   49    69  143  413  1920         618  2015-16
6301       2544  LeBron James   LeBron  1610612739               CLE 32.00  74  51  23   0.69 2794.57  736  1344    0.55   124   342     0.36  358  531    0.67    97   542  639  646  303   92   44    60  134  440  1954         483  2016-17
6820       2544  LeBron James   LeBron  1610612739               CLE 33.00  82  50  32   0.61 3025.59  857  1580    0.54   149   406     0.37  388  531    0.73    97   612  709  747  347  116   71    68  136  439  2251         105  2017-18
7365       2544  LeBron James   LeBron  1610612747               LAL 34.00  55  28  27   0.51 1937.40  558  1095    0.51   111   327     0.34  278  418    0.67    57   408  465  454  197   72   33    52   94  320  1505         116  2018-19
7892       2544  LeBron James   LeBron  1610612747               LAL 35.00  67  50  17   0.75 2316.27  643  1303    0.49   148   425     0.35  264  381    0.69    66   459  525  684  261   78   36    59  118  339  1698         442  2019-20
8427       2544  LeBron James   LeBron  1610612747               LAL 36.00  45  30  15   0.67 1503.70  422   823    0.51   104   285     0.36  178  255    0.70    29   317  346  350  168   48   25    27   70  206  1126         287  2020-21
9008       2544  LeBron James   LeBron  1610612747               LAL 37.00  56  25  31   0.45 2084.34  640  1221    0.52   161   448     0.36  254  336    0.76    63   396  459  349  196   73   59    46  121  306  1695        -117  2021-22
9571       2544  LeBron James   LeBron  1610612747               LAL 38.00  55  30  25   0.55 1953.94  609  1219    0.50   121   377     0.32  251  327    0.77    65   392  457  375  178   50   32    47   88  273  1590         214  2022-23

In [28]:
greatest_season_lebron_era = lebron_era_stats_df.loc[lebron_era_stats_df['PTS'].idxmax()]

In [34]:
greatest_season_jordan_era = jordan_era_stats_df.loc[jordan_era_stats_df['PTS'].idxmax()]

In [29]:
greatest_season_lebron_era

PLAYER_ID                    977
PLAYER_NAME          Kobe Bryant
NICKNAME                    Kobe
TEAM_ID               1610612747
TEAM_ABBREVIATION            LAL
AGE                        27.00
GP                            80
W                             45
L                             35
W_PCT                       0.56
MIN                      3277.10
FGM                          978
FGA                         2173
FG_PCT                      0.45
FG3M                         180
FG3A                         518
FG3_PCT                     0.35
FTM                          696
FTA                          819
FT_PCT                      0.85
OREB                          71
DREB                         354
REB                          425
AST                          360
TOV                          250
STL                          147
BLK                           30
BLKA                          82
PF                           233
PFD                          650
PTS                         2832
PLUS_MINUS                   318
SEASON                   2005-06
Name: 1163, dtype: object

In [25]:
greatest_season_jordan_era = jordan_era_stats_df.loc[jordan_era_stats_df['PTS'].idxmax()]

In [35]:
greatest_season_jordan_era

PLAYER_ID                       893
PLAYER_NAME          Michael Jordan
NICKNAME                    Michael
TEAM_ID                  1610612741
TEAM_ABBREVIATION               CHI
AGE                           34.00
GP                               82
W                                69
L                                13
W_PCT                          0.84
MIN                         3108.80
FGM                             920
FGA                            1892
FG_PCT                         0.49
FG3M                            111
FG3A                            297
FG3_PCT                        0.37
FTM                             480
FTA                             576
FT_PCT                         0.83
OREB                            113
DREB                            369
REB                             482
AST                             352
TOV                             166
STL                             140
BLK                              44
BLKA                             49
PF                              156
PFD                               2
PTS                            2431
PLUS_MINUS                      820
SEASON                      1996-97
Name: 308, dtype: object